name: Push JavaVersionManager.exe to Release Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync_exe_to_release:
    runs-on: windows-latest

    steps:
      # Checkout the main branch
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: false  # Disable submodules if not needed

      # Build the EXE file
      - name: Install Inno Setup and Build EXE File
        run: |
          choco install innosetup -y  # Install Inno Setup Compiler
          iscc.exe "setup.iss"  # Build the EXE file

      # Verify that the EXE file is created
      - name: Verify EXE File
        run: |
          if (-Not (Test-Path "JavaVersionManager.exe")) {
              throw "JavaVersionManager.exe not found after build."
          }

      # Configure Git Identity
      - name: Configure Git Identity
        run: |
          git config --global user.name "PushpaKumara89"  # Set Git username
          git config --global user.email "kpushpakumarajd@gmail.com"  # Set Git email

      # Switch to the release branch and push the EXE file
      - name: Push JavaVersionManager.exe to Release Branch
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use a secure token for authentication
        run: |
          git remote set-url origin https://$TOKEN@github.com/PushpaKumara89/test.git
          git checkout -b release || git checkout release
          git add JavaVersionManager.exe
          git commit -m "Add JavaVersionManager.exe from main" || echo "No changes to commit"
          git push -u origin release || echo "Push failed"

      # Debugging: Verify the files in the release branch
      - name: Debugging - List Files in Release Branch
        run: |
          Get-ChildItem -Recurse  # List all files and directories recursively
          git status  # Display the current Git status
