name: Push JavaVersionSwitcher.exe to Release Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync_exe_to_release:
    runs-on: windows-latest

    steps:
      # Checkout the main branch
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: false  # Disable submodules if not needed

      # Build the EXE file
      - name: Install Inno Setup and Build EXE File
        run: |
          choco install innosetup -y  # Install Inno Setup Compiler
          iscc.exe "setup.iss"  # Build the EXE file

      # Verify that the EXE file is created
      - name: Verify EXE File
        run: |
          if (-Not (Test-Path "JavaVersionSwitcher.exe")) {
              throw "JavaVersionSwitcher.exe not found after build."
          }

      # Configure Git Identity
      - name: Configure Git Identity
        run: |
          git config --global user.name "PushpaKumara89"  # Set Git username
          git config --global user.email "kpushpakumarajd@gmail.com"  # Set Git email

      # Switch to the release branch and push the EXE file
      - name: Push JavaVersionSwitcher.exe to Release Branch
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use a secure token for authentication
        run: |
          git remote set-url origin https://$TOKEN@github.com/PushpaKumara89/Java-Version-Switcher.git
          git checkout -b release1.0.2 || git checkout release1.0.2
          git add JavaVersionSwitcher.exe
          git commit -m "Add JavaVersionSwitcher.exe from main" || echo "No changes to commit"
          git push -u origin release1.0.2 || echo "Push failed"

      # Debugging: Verify the files in the release branch
      - name: Debugging - List Files in Release Branch
        run: |
          Get-ChildItem -Recurse  # List all files and directories recursively
          git status  # Display the current Git status